<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKq9YHam\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKq9YHam/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKq9YHam.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKq9YHam\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKq9YHam\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kq9YHam',
    'container.build_id' => 'ac8f15cd',
    'container.build_time' => 1652826740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKq9YHam');
