<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'prix_produit' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'prix_produit' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->prix_produit);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'type_produit', 'prix_produit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'date_expo', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'date_fin', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'disponibilite', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'type_action', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imgproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'ligneCommandes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'commandes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'type_produit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'date_expo', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'date_fin', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'disponibilite', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'type_action', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imgproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'ligneCommandes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'commandes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->prix_produit);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeProduit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeProduit', []);

        return parent::getTypeProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeProduit(string $type_produit): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeProduit', [$type_produit]);

        return parent::setTypeProduit($type_produit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixProduit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixProduit', []);

        return parent::getPrixProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixProduit(string $prix_produit): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixProduit', [$prix_produit]);

        return parent::setPrixProduit($prix_produit);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgproduit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgproduit', []);

        return parent::getImgproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgproduit(string $imgproduit): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgproduit', [$imgproduit]);

        return parent::setImgproduit($imgproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpo(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpo', []);

        return parent::getDateExpo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpo(\DateTimeInterface $date_expo): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpo', [$date_expo]);

        return parent::setDateExpo($date_expo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(\DateTimeInterface $date_fin): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$date_fin]);

        return parent::setDateFin($date_fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilite', []);

        return parent::getDisponibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilite(string $disponibilite): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilite', [$disponibilite]);

        return parent::setDisponibilite($disponibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAction(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAction', []);

        return parent::getTypeAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAction(string $type_action): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAction', [$type_action]);

        return parent::setTypeAction($type_action);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneCommandes', []);

        return parent::getLigneCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneCommande(\App\Entity\LigneCommande $ligneCommande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneCommande', [$ligneCommande]);

        return parent::addLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneCommande(\App\Entity\LigneCommande $ligneCommande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneCommande', [$ligneCommande]);

        return parent::removeLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function setUp($type_produit, $type_action, $disponibilite, $prix_produit, $date_expo, $date_fin, $imgproduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUp', [$type_produit, $type_action, $disponibilite, $prix_produit, $date_expo, $date_fin, $imgproduit]);

        return parent::setUp($type_produit, $type_action, $disponibilite, $prix_produit, $date_expo, $date_fin, $imgproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\App\Entity\Commande $commande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\App\Entity\Commande $commande): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

}
